import MDAnalysis as mda 
from MDAnalysis.analysis import rdf
import numpy as np
import matplotlib.pyplot as plt
u = mda.Universe('traj.pdb')
Cl = u.select_atoms('name Cl')
O = u.select_atoms('name O')
Ca = u.select_atoms('name Ca')
H = u.select_atoms('name H')
rdf1 = mda.analysis.rdf.InterRDF(Cl, O, nbins=100, range=(0.0,19.0))
rdf2 = mda.analysis.rdf.InterRDF(Ca, O, nbins=100, range=(0.0,19.0))
rdf3 = mda.analysis.rdf.InterRDF(Cl, H, nbins=100, range=(0.0,19.0))
rdf4 = mda.analysis.rdf.InterRDF(Ca, Cl, nbins=100, range=(0.0,19.0))
rdf5 = mda.analysis.rdf.InterRDF(Ca, H, nbins=100, range=(0.0,19.0))
rdf1.run()
rdf2.run()
rdf3.run()
rdf4.run()
rdf5.run()
np.save('rdf-cl-o', np.transpose([rdf1.results.bins, rdf1.results.rdf]))
np.save('rdf-ca-o', np.transpose([rdf2.results.bins, rdf2.results.rdf]))
np.save('rdf-cl-h', np.transpose([rdf3.results.bins, rdf3.results.rdf]))
np.save('rdf-ca-cl', np.transpose([rdf4.results.bins, rdf4.results.rdf]))
np.save('rdf-ca-h', np.transpose([rdf5.results.bins, rdf5.results.rdf]))
clo=np.load("rdf-cl-o.npy")
cao=np.load("rdf-ca-o.npy")
ho=np.load("rdf-cl-h.npy")
cacl=np.load("rdf-ca-cl.npy")
cah=np.load("rdf-ca-h.npy")
np.savetxt('cl-o.txt',clo)
np.savetxt('ca-o.txt',cao)
np.savetxt('cl-h.txt',ho)
np.savetxt('ca-cl.txt',cacl)
np.savetxt('ca-h.txt',cah)
#rdf_data = np.load("rdf-cl-o.dat.npy")
#x = rdf_data[:,0]
#y = rdf_data[:,1]
#plt.plot(x,y,label="DPMD")
#plt.legend(loc="upper right")
#plt.xlabel("r(Å)")
#plt.ylabel("gCl-o(r)")
#plt.title("RDF plot")
#plt.show()
